// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  CORS_ORIGIN: string;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  PAYSTACK_SECRET_KEY: string;
  R2_PUBLIC_URL: string;
  NODE_ENV: string;
  BUCKET: R2Bucket;
  DB: D1Database;
}
