name = "azumi-server"
main = "src/index.ts"
compatibility_date = "2025-03-15"
compatibility_flags = ["nodejs_compat","nodejs_compat_populate_process_env"]

[observability]
enabled = true

# Weekly vendor payout job - runs every Sunday at 00:01 AM
# [triggers]
# crons = ["1 0 * * 0"]

# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

# Uncomment the following sections as needed:

[placement]
mode = "smart"

[[d1_databases]]
binding = "DB"
database_name = "azumi-db"
database_id = "07b109be-83d0-41f7-a47f-1ce49611bc18"

# [[durable_objects.bindings]]
# name = "ORDER_NOTIFICATION"
# class_name = "OrderNotification"

# [[migrations]]
# tag = "v1"
# new_sqlite_classes = ["OrderNotification"]

[env.staging]
   
    vars = { CLIENT_URL = "http://localhost:5173/" }
    d1_databases = [{ binding = "DB", database_name = "azumi-db-staging", database_id = "86c0adbb-631d-4416-a1e9-6f83e680c12e" }]
    r2_buckets = [{ bucket_name = "azumi-staging-bucket", binding = "BUCKET" }]
workflows =[{ name = "order-processing", binding = "ORDER_WORKFLOW", class_name = "OrderWorkflow" }]
        durable_objects.bindings = [ { name = "ORDER_NOTIFICATION", class_name = "OrderNotification" } ]
    migrations = [ { tag = "v1", new_sqlite_classes = ["OrderNotification"] } ]
    


[env.production]

    d1_databases = [ { binding = "DB", database_name = "azumi-db", database_id = "07b109be-83d0-41f7-a47f-1ce49611bc18" } ]
    r2_buckets = [{ bucket_name = "azumi-bucket", binding = "BUCKET" }]

