CREATE TABLE `riders` (
	`id` text PRIMARY KEY NOT NULL,
	`first_name` text,
	`last_name` text,
	`phone_number` text,
	`email` text,
	`address` text,
	`longitude` real,
	`latitude` real,
	`address_name` text,
	`vehicle_type` text,
	`vehicle_license` text,
	`identification_document` text,
	`application_status` text DEFAULT 'DRAFT',
	`active` integer DEFAULT false,
	`availability_status` text DEFAULT 'OFFLINE',
	`rating` real DEFAULT 0,
	`total_ratings` integer DEFAULT 0,
	`is_verified` integer DEFAULT false,
	`bank_info` text,
	`max_delivery_distance` integer DEFAULT 10000,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`id`) REFERENCES `user_table`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `reviews` (
	`id` text PRIMARY KEY NOT NULL,
	`order_id` text,
	`user_id` text,
	`shop_id` text,
	`rider_id` text,
	`food_rating` integer,
	`delivery_rating` integer,
	`comment` text,
	`images` text,
	`reply` text,
	`reply_at` integer,
	`created_at` integer,
	`updated_at` integer,
	FOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`user_id`) REFERENCES `user_table`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`shop_id`) REFERENCES `shop_table`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`rider_id`) REFERENCES `riders`(`id`) ON UPDATE no action ON DELETE no action
);
